# Generated by Django 3.2.4 on 2021-06-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craig_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
        migrations.RenameField(
            model_name='search',
            old_name='created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='search',
            new_name='search_text',
        ),
    ]
